name: Deploy logs worker 

on:
  push:
    branches:
      - develop
      - main
jobs:
  publish:
    name: Init Logs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Use Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm i

    - name: List files
      run: ls 

    - name: Install wrangler logs
      run: npm install -g wrangler

    - name: Init Logs
      uses: cloudflare/wrangler-action@2.0.0
      with:
        apiToken: ${{ secrets.cloudflare_api_key }}
        command: tail e-com
